export const API_URL = 'https://www.nftcoffins.com/api/'
export const OPEN_SEA_URL = 'https://opensea.io/collection/nftcoffins'
export const OPEN_SEA_TOKEN_BASE_URL = 'https://opensea.io/assets/0xf7a0be0ebb60eae52f9340cc5fa136fcfde4744e/'
export const WEB_IMAGE_NAME = 'web.png'
export const FOR_SALE_ANCHOR_ID = 'for-sale'